org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true


minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.235
loader_version_range=[1,)

mod_id=axess
mod_name=aXess
mod_license=GPL-3.0
mod_version=0.3.3-neoforge.1
mod_group_id=net.teekay
mod_authors=Teekay
mod_description=Simple mod that adds keycards and keycard networks!
